### ISSUE TITLE
tool does not recognize new wild cards

### ISSUE THREAD

**Issue by rizeladiaz** [STScI-MESA/reference-file-testing-tool#3]
I ran into this problem when testing a CRDS file:
> test_reference_file /grp/crds/jwst/references/jwst/jwst_nirspec_refpix_0001.fits 

Connected to DB at /grp/jwst/ins/reference-file-testing-tool/testdata/sic_dil.db
Searching DB for test data with
    DETECTOR = NRS1
    READPATT = ALLIRS2
Found 0 instances:
    No matches found

CRDS changed the way in which they are handling the "or" option. instead of using READPATT=X|Y (i.e. or), it uses the "P_something" keyword. And then it uses a sort of whild card (like generic) for the real array.  Your tool has to be able to read not this new P_ value in order to identify what dataset to use.

**Comment by mattjhill** [comment]
I'm not sure what you mean.

Are you saying that I should use e.g. P_READPA to find test data? And that keyword will have a X|Y value?  Does this apply to all reference files or only those with an or condition?

**Comment by mattjhill** [comment]
The reference file you are using has no P_* header keywords.

**Comment by mattjhill** [comment]
This has been implemented.
