### ISSUE TITLE
Drop Create and Remove functionality from db_utils

### ISSUE THREAD

**Issue by mfixstsci** [STScI-MESA/reference-file-testing-tool#6]
Drop add and remove database functionality in the future. For right now drop remove before merging refactor branch into master.

**Comment by mfixstsci** [comment]
Dropped remove functionality. Will leave issue open until we drop the create functionality. In the long run we hope to host the regression suite of data on a mysql db server. This was the user won't have to create, remove, add, populate data etc. 

33e16f3

**Comment by stscicrawford** [comment]
There might be use cases that a person might want to create their own database.  So I think it would be okay to leave in the functionality and close this issue.

**Comment by mfixstsci** [comment]
Agreed, I like that idea. I'll go ahead and close it.
